sudo: required
addons:
  apt:
    packages:
    - libguestfs-tools
    - wget
env:
  - LIBGUESTFS_BACKEND=direct
before_script:
  - wget http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
  - sudo chmod +x test.sh
script:
  - sudo ./test.sh
after_script:
  - echo "Build success"
