version: '3'
services:
  squid:
    build: squid
    image: aahad91/squid
    ports:
      - "3128:3128"
    networks:
      squid-test:
        ipv4_address: 172.20.0.2
    tty: true

  client:
    build: squid/client
    image: aahad91/vnf_client
    environment:
            HTTP_PROXY: http://172.20.0.2:3128
    networks:
      squid-test:
        ipv4_address: 172.20.0.3
    tty: true
  web-server:
    build: squid/client_ws
    image: aahad91/apache_server
    networks:
      squid-test:
        ipv4_address: 172.20.0.4
    tty: true
networks:
  squid-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
