descriptor_extension: yml
version: '0.5'
files:
- path: ns_squid.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
- path: vnf_squid.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
package:
  name: ns_squid
  version: '0.1'
  maintainer: Abdul Ahad
  vendor: de.upb.cn
  description: pg-backflip
