FROM ubuntu:latest

RUN apt-get -y update

RUN DEBIAN_FRONTEND=noninteractive \
apt-get install -y squid

COPY squid.conf /etc/squid/squid.conf

EXPOSE 3128
ENTRYPOINT service squid restart && bash 
 

